name: Live Futebol H WebRadio

on:
  schedule:
    # Quinta-feira (11/06) - 13:45 às 20:30 BRT -> 16:45 às 23:30 UTC
    - cron: '45 16 11 6 *'
    
    # Sábado (13/06) - 18:00 às 21:30 BRT -> 21:00 às 00:30 UTC
    - cron: '0 21 13 6 *'
    
    # Sexta-feira (19/06) - 20:30 às 23:30 BRT -> 23:30 às 02:30 UTC
    - cron: '30 23 19 6 *'
    
    # Quarta-feira (24/06) - 18:00 às 21:30 BRT -> 21:00 às 00:30 UTC
    - cron: '0 21 24 6 *'
    
  workflow_dispatch: # Botão para você testar na hora que quiser

jobs:
  retransmitir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Instalar FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Iniciar Script Python
        run: python3 retransmitir_futebol.py
