name: Super Playlist Spotify Manual

on:
  workflow_dispatch: # Botão para rodar manual na aba Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install spotdl

      - name: Rodar Sincronização Spotify
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
        run: python gerador_inteligente.py
