name: Super Playlist Gemini (3 em 3 dias)

on:
  schedule:
    - cron: '0 5 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Instalar Dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install yt-dlp google-generativeai

      - name: Rodar Gerador Gemini
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASS: ${{ secrets.FTP_PASS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python gerador_inteligente.py
